table ref_job_positions
	lineageTag: c6ad059b-91b3-4e83-b2a0-1919aec754db

	column job_position_id
		dataType: int64
		formatString: 0
		lineageTag: f8a28cd7-9549-4e08-9339-8c51d9daea5a
		summarizeBy: none
		sourceColumn: job_position_id

		annotation SummarizationSetBy = Automatic

	column role
		dataType: string
		lineageTag: 3ee17ba0-d41b-4b6f-87d6-d4cbe7585116
		summarizeBy: none
		sourceColumn: role

		annotation SummarizationSetBy = Automatic

	column job_position_status
		dataType: string
		lineageTag: 721b37cb-e190-44a1-b55a-8fbea0b9db3f
		summarizeBy: none
		sourceColumn: job_position_status

		annotation SummarizationSetBy = Automatic

	column signed_off
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d99444c8-e213-4702-a415-f1aa8a7e074c
		summarizeBy: none
		sourceColumn: signed_off

		annotation SummarizationSetBy = Automatic

	column organisation_id
		dataType: int64
		formatString: 0
		lineageTag: 95dfaf70-178c-45c6-a574-b32fa76730a1
		summarizeBy: sum
		sourceColumn: organisation_id

		annotation SummarizationSetBy = Automatic

	partition ref_job_positions = m
		mode: import
		queryGroup: References
		source =
				let
				    Source = PostgreSQL.Database("dpg-d09mf0muk2gs73dl8nm0-a.frankfurt-postgres.render.com:5432", "drfocused_mp"),
				    public_ref_job_positions = Source{[Schema="public",Item="ref_job_positions"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_ref_job_positions,{{"signed_off", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

