table ref_references
	lineageTag: b885eee8-b7ee-4f2f-9ec6-ed55be4ca767

	measure 'Avg Requested To Reviewed Time' = AVERAGE(ref_references[requested_to_reviewed_time])
		lineageTag: 041a0674-71e9-4b34-9cad-d74563756b46

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Requested To Submitted Time' = AVERAGE(ref_references[requested_to_completed_time])
		lineageTag: 66928b21-7fd6-46c2-9aad-085899a5ff6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Submitted To Reviewed Time' = AVERAGE(ref_references[completed_to_reviewed_time])
		lineageTag: 385f93cf-9173-4941-862c-8656e5462482

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Number of Approved References' = COUNT(ref_references[ref_approved_at])
		formatString: 0
		lineageTag: 1669d29c-abae-4076-8450-325285ca51c5

	measure 'Number of Submitted References' = COUNT(ref_references[requested_to_completed_time])
		formatString: # ##0
		lineageTag: 571e7b98-73cc-4750-8f12-2cb3d219067f

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Number of Months for Rolling Avg' = 3
		formatString: 0
		lineageTag: 7265594d-34ca-4b81-8e8e-a893d41f95d1

	measure 'Number of References' = COUNTROWS(ref_references) + 0
		formatString: # ##0
		lineageTag: fe038b7a-df2e-4144-9133-1f64b61e0628

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Rolling Avg Submitted to Reviewed Days' = ```
			
			CALCULATE (
			    AVERAGEX (ref_references, ref_references[completed_to_reviewed_time]),
			    DATESINPERIOD (
			        Dates[Date],
			        LASTDATE (Dates[Date]),
			        -[Number of Months for Rolling Avg],
			        MONTH
			    ),
			    USERELATIONSHIP(
			        ref_references[ref_approved_date], 
			        Dates[Date]
			    )
			) / (60*60*24)
			```
		lineageTag: 7bc574af-90e6-4521-8da0-d2d37e48ebbe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rolling Avg Requested to Submitted Days' =
			
			CALCULATE (
			    AVERAGEX (ref_references, ref_references[requested_to_completed_time]),
			    DATESINPERIOD (
			        Dates[Date],
			        LASTDATE (Dates[Date]),
			        -[Number of Months for Rolling Avg],
			        MONTH
			    )
			) / (60*60*24)
		lineageTag: 7782a940-1041-4e40-aec4-6602b6abdc92

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rolling Avg Requested to Reviewed Days' =
			
			CALCULATE (
			    AVERAGEX (ref_references, ref_references[requested_to_reviewed_time]),
			    DATESINPERIOD (
			        Dates[Date],
			        LASTDATE (Dates[Date]),
			        -[Number of Months for Rolling Avg],
			        MONTH
			    )
			) / (60*60*24)
		lineageTag: 05c43ece-3a31-45a5-b65d-28685ca8eab2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column completed_to_reviewed_days
		dataType: int64
		lineageTag: 23629e9c-98e8-470a-b6a3-04d973f3462c
		summarizeBy: none
		sourceColumn: completed_to_reviewed_days

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation SummarizationSetBy = User

	column completed_to_reviewed_time
		dataType: double
		lineageTag: 0e6cfed2-2615-438d-af84-6853ec889c5f
		summarizeBy: sum
		sourceColumn: completed_to_reviewed_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cr_created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: fd8ae5a7-4295-4dd8-9852-84ddfb7abde8
		summarizeBy: none
		sourceColumn: cr_created_at

		annotation SummarizationSetBy = Automatic

	column job_position_id
		dataType: int64
		formatString: 0
		lineageTag: 499c4c8c-744c-4b9e-91a0-f720075f052c
		summarizeBy: none
		sourceColumn: job_position_id

		annotation SummarizationSetBy = Automatic

	column marked_compliant_at
		dataType: dateTime
		formatString: General Date
		lineageTag: a3f7d584-2d3c-4e2a-916e-34adf2da4340
		summarizeBy: none
		sourceColumn: marked_compliant_at

		annotation SummarizationSetBy = Automatic

	column ref_approval_status
		dataType: string
		lineageTag: 8d140338-c260-4689-9f92-89a606f666b5
		summarizeBy: none
		sourceColumn: ref_approval_status

		annotation SummarizationSetBy = Automatic

	column ref_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 7ff57eb8-6ca7-45bc-8b04-619c291f01da
		summarizeBy: none
		sourceColumn: ref_approved_at

		annotation SummarizationSetBy = Automatic

	column ref_approved_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 76e1ce4e-a2eb-41ef-9759-f80f2c52078d
		summarizeBy: none
		sourceColumn: ref_approved_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ref_completed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: d8c991f5-3ad3-49b5-bc02-afffa731d9c2
		summarizeBy: none
		sourceColumn: ref_completed_at

		annotation SummarizationSetBy = Automatic

	column ref_completed_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3416eb6a-af72-4a4e-bbca-e8c90d25fd42
		summarizeBy: none
		sourceColumn: ref_completed_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ref_requested_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 5a78b2db-c16f-4097-9d11-45e497daa335
		summarizeBy: none
		sourceColumn: ref_requested_at

		annotation SummarizationSetBy = Automatic

	column ref_requested_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f94f6bd6-c89f-4c1e-ab96-c1ca3e7bc6e8
		summarizeBy: none
		sourceColumn: ref_requested_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ref_status
		dataType: string
		lineageTag: b6f45942-620d-438f-be38-a38cb51882ce
		summarizeBy: none
		sourceColumn: ref_status

		annotation SummarizationSetBy = Automatic

	column requested_to_completed_days
		dataType: int64
		lineageTag: 17416bd8-6afd-44af-b464-b18d86d98f13
		summarizeBy: none
		sourceColumn: requested_to_completed_days

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation SummarizationSetBy = User

	column requested_to_completed_time
		dataType: double
		lineageTag: 483615f0-6590-491f-ac76-7bdf4057728f
		summarizeBy: sum
		sourceColumn: requested_to_completed_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column requested_to_compliant_time
		dataType: double
		lineageTag: bcc01aa2-fa25-47b3-b88e-c408aef4b799
		summarizeBy: sum
		sourceColumn: requested_to_compliant_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column requested_to_reviewed_time
		dataType: double
		lineageTag: 3b27de7d-a880-4f41-bc8b-ad7f7f23dd2c
		summarizeBy: sum
		sourceColumn: requested_to_reviewed_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_mandatory
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2a337263-ea0e-42e8-ac94-380320303a74
		summarizeBy: none
		sourceColumn: is_mandatory

		annotation SummarizationSetBy = Automatic

	column ref_package_name
		dataType: string
		lineageTag: f2df5504-f1f0-4fe6-a5fe-b5767d3b808a
		summarizeBy: none
		sourceColumn: ref_package_name

		annotation SummarizationSetBy = Automatic

	column ref_form_name
		dataType: string
		lineageTag: 650694b2-e78a-4195-8b90-28f49af2635b
		summarizeBy: none
		sourceColumn: ref_form_name

		annotation SummarizationSetBy = Automatic

	column requested_to_reviewed_days
		dataType: int64
		formatString: 0
		lineageTag: 31e40869-eec8-4f09-9626-6adfa1b69822
		summarizeBy: sum
		sourceColumn: requested_to_reviewed_days

		annotation SummarizationSetBy = Automatic

	column requested_to_compliant_days
		dataType: int64
		formatString: 0
		lineageTag: 1906c848-5dc3-4fbb-b228-a28e9979dae9
		summarizeBy: sum
		sourceColumn: requested_to_compliant_days

		annotation SummarizationSetBy = Automatic

	column requested_to_completed_category
		dataType: string
		lineageTag: 9fb2884c-3945-411f-b837-54ba671bdf7f
		summarizeBy: none
		sourceColumn: requested_to_completed_category

		annotation SummarizationSetBy = Automatic

	column completed_to_reviewed_category
		dataType: string
		lineageTag: 3ca37f9b-3613-443a-b375-4a7c0d7fff60
		summarizeBy: none
		sourceColumn: completed_to_reviewed_category

		annotation SummarizationSetBy = Automatic

	column requested_to_reviewed_category
		dataType: string
		lineageTag: 28fffcf8-e23d-4649-8175-8cf94d2eb78f
		summarizeBy: none
		sourceColumn: requested_to_reviewed_category

		annotation SummarizationSetBy = Automatic

	column requested_to_compliant_category
		dataType: string
		lineageTag: 8af4e4f7-15d3-4e37-abe8-6a9aa4663f24
		summarizeBy: none
		sourceColumn: requested_to_compliant_category

		annotation SummarizationSetBy = Automatic

	partition ref_references = m
		mode: import
		queryGroup: References
		source =
				let
				    Source = PostgreSQL.Database("dpg-d09mf0muk2gs73dl8nm0-a.frankfurt-postgres.render.com:5432", "drfocused_mp"),
				    public_ref_references = Source{[Schema="public",Item="ref_references"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_ref_references,{{"requested_to_completed_time", type number}, {"completed_to_reviewed_time", type number}, {"requested_to_reviewed_time", type number}, {"requested_to_compliant_time", type number}, {"requested_to_completed_days", Int64.Type}, {"completed_to_reviewed_days", Int64.Type}, {"requested_to_reviewed_days", Int64.Type}, {"requested_to_compliant_days", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

